version: "3.7"
services:
  db:    
    container_name: SQLServer
    build: ./db  
    image: andresgarcia0313/sql:latest
    environment:    
      DEBUG: 1
      ACCEPT_EULA: Y
      SA_PASSWORD: "Asde71.4"    # MSSQL_PID: Express #
      MSSQL_PID: Developer
      MSSQL_AGENT_ENABLED: "true"    # 
      MSSQL_MEMORY_LIMIT_MB: 512
    ports:
      - 1433:1433
    volumes:
      - ./db/scriptSQL:/sqlScript
      - ./db/data:/var/opt/mssql/data
      - ./db/log:/var/opt/mssql/log
      - ./db/secrets:/var/opt/mssql/secrets